// <auto-generated />
namespace DataLayer.Migration.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class update11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update11));
        
        string IMigrationMetadata.Id
        {
            get { return "201911061833160_update11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
