// <auto-generated />
namespace DataLayer.Migration.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class update161 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update161));
        
        string IMigrationMetadata.Id
        {
            get { return "201911111441447_update161"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
